import React, { FC } from 'react';
import Head from 'next/head';
import styles from '../../../styles/Home.module.css';
import SelectList from '../../organisms/SelectList';
import ChartBox from '../../organisms/ChartBox';

export type Item = {
  id: string;
  label: string;
  checked: boolean;
  handleClick: () => void;
};

type Props = {
  title: string;
  items: Item[];
  data: {
    year: number;
    [name: string]: number;
  }[];
  isDataLoading: boolean;
};

const HomeTemplate: FC<Props> = ({ title, items, data, isDataLoading }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <SelectList items={items} />
        </div>
      </main>
      <div>
        {isDataLoading ? <div>Loading...</div> : <ChartBox data={data} />}
      </div>
      <footer className={styles.footer} />
    </div>
  );
};

export default HomeTemplate;
